# Generated by Django 3.1.5 on 2021-01-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0005_auto_20210119_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='attachment_file',
            field=models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/%d'),
        ),
    ]
