# Generated by Django 3.1.5 on 2021-01-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0007_auto_20210119_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
