# Generated by Django 3.1.5 on 2021-01-19 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0008_auto_20210119_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='asked_by',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Users'}, on_delete=django.db.models.deletion.CASCADE, related_name='asked_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
