# Generated by Django 3.1.5 on 2021-01-19 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0010_auto_20210119_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresponse',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_v1.questions'),
        ),
    ]
